language: python

python:
  # - "3.5" # Doesn't work because of f-strings
  - "3.6"
  # No need to test for higher versions
  # - "3.7"
  # - "3.8"

install:
  - pip install coveralls

before_script:
  # - git submodule update --init # Make sure Pyramid-Scheme submodule is up to date
  - ls -lh
  - ls Pyramid-Scheme/ -lh
  - python -c "import sys; print(sys.version, '\n', sys.prefix)"
  - python -m pip install 'more_itertools>=8.5.0'

script:
  - bash run_coverage # <- This runs tests for the main files too
  - python -m unittest discover -p "test_examples.py" tests -v

after_success:
  - echo == ALL TESTS PASSED ==
  - coveralls

after_failure:
  - echo == FAILURE ==