language: python

python:
  - "3.6"
  - "3.7"

# install:
  # - pip install more_itertools
  
script:
  - python -c "import sys; print(sys.version, '\n', sys.prefix)"
  - python -m unittest discover tests -v

after_success:
  - echo == ALL TESTS PASSED ==

after_failure:
  - echo == FAILURE ==