language: python

python:
  # - "3.5" # Doesn't work because of f-strings
  - "3.6"
  # No need to test for higher versions
  # - "3.7"
  # - "3.8"

install:
  - pip install coveralls
  
script:
  - python -c "import sys; print(sys.version, '\n', sys.prefix)"
  # - coverage run -m unittest discover tests -v
  - bash run_coverage

after_success:
  - echo == ALL TESTS PASSED ==
  - coveralls

after_failure:
  - echo == FAILURE ==